notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=tgarc
    - secure: "jK9hKnRawtZVNmx+mOZ0QYPYtpuC/34TDFwR2PQrqH98qGQkOkvHKAv5OAGcOqjpOVJ7dyiHW+SUMqN7ruyinmFvQIniW59xtg/7t4+SSZO4XnhyYCOjlbcuzNj0N6dueiFuJVnESGFlVdqdsTsldxD0TN4Pm1VTpqbC2J0OuAAmSaUn92Ybt9boxhOw/KupnDio0AUZEHnad3ctgw1Mt3faJkrHbdgRo1VNUjtDwQufMdSUwfyQ5FyQp4WOHnDldgGZIzjVYA4/0D6pXJ/XQzniiuT7lWR/s1vYJdgniZm+4mEV6/V99y6/ZKH/93iWIRWtR4D0XzIpJvALR8v6/A8frx7qaLo4Q04dwhGTzO6HtsOpOun+V0e2RW3UAHG51MjFF2bOy2ySiS9dlIVcWCMZsWJoa/D1NgSWiQdJmYPs2Q5RjwEoVpYVW9y7d0t0cep3811+WsHU92Mn/gryxaYYArxJI46n68dQoGqCub/11jAViZucbJVkThdGsLoRy/5CnB/2HyXPs6rBvJcza87bi4Nh3SyW4ZmHuk+i/6iKU46393AHQ4S0RXx0d3aLf94Cd9qafA++5nXeDMYnuDbPMB1cRLi3ur03afdJUUyuD8I1yAUKso4R6UhWKkNdmKIrwGZeYmHcqKnxZ3G/PRjRK4n/tnFqXma4MXzJaks="
    - CIBW_BEFORE_BUILD_LINUX='yum install -y libffi-devel'
    # - CIBW_TEST_COMMAND='pytest {project}/test_pastream.py'

matrix:
  include:
    - os: linux
      sudo: required
      services:
        - docker
    - os: osx
      env: PKG_CONFIG_PATH="$PKG_CONFIG_PATH":/usr/local/opt/libffi/lib/pkgconfig
      language: generic
      before_install:
        - brew install libffi
        - virtualenv env -p python
        - source env/bin/activate

script:
  - pip install cibuildwheel twine
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG = *rc* ]]; then
        twine upload wheelhouse/*.whl --repository-url https://testpypi.python.org/pypi --skip-existing
    elif [[ $TRAVIS_TAG ]]; then
        twine upload wheelhouse/*.whl --skip-existing
    fi

__base_deploy: &base_deploy
  provider: pypi
  skip_upload_docs: true
  distributions: sdist
  user: tgarc
  password:
    secure: "Jho97tbtWNfGTxdYBmJGjT3wf8XyKtY/pSgx4JSHCMtR4BfyDibRBe8HYP7wPFckt4v477qRP51HhAGsKpLMgeAInC0NFvYY7v6BijyyRs2zbAkXjM30oP/okz+IcYy5xMBY8Q7PwZRPppi0qrbi8qY4T/hgRh9u+hRXVVxxz/Ti6WVRwBGc8qF+2wWXzn4ekdJ2Xuwm9lhvuKtezU/2+1+FkvlXf0Xr5zP/IcdBRdnWIxSZr/M2/4vif1mFwNbRQCXS3gaFuE5OlMJbutXOsh41suiy7Yc9TLGq5ozZZHRjQMHoLPPvs5TK37W1TOqDLJtqdDvX49HGgE2AxxeNdevZx2oLquwywZxat3wgBA7dju5AZXhhXTDvDtsWXTe5cTIV8BsvJrTSyKG+Zr5g0uxSuw7eC06E5BdDk7m2sq4jZu846EqsNlTX0EsM5ogy9uc1SZe0YG/4u+6RLj0dcuEB8QQISPtjqv0kvzAtC3G7GVYf95eE9Iea04J0SFp8fswd3ndyg0dgJgvF23nlDMekZnPWvcNTH425YvLuW8eDvU4BpnrBjy8hIWWCEHNnywYDfDvu4D0DvtVNnX7gTyUZhDJikTsfyXpUhn9t1Oye8byt083ms89DEbcEgIGbhw9a+TkX+Or4IH2+PehQbXF1P5FruXXPnkXO//K+bu4="

deploy:
  # test deploy
  - <<: *base_deploy
    server: https://testpypi.python.org/pypi
    on:
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_TAG = *rc*
      tags: true
  # release deploy
  - <<: *base_deploy
    on:
      condition: $TRAVIS_OS_NAME = linux && $TRAVIS_TAG != *rc*
      tags: true
