notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

environment:
  TWINE_USERNAME: tgarc
  TWINE_PASSWORD:
    secure: DOd96g4ffAQbXuqMwLlpMw==

install:
  - git submodule update --init --recursive
  - python -m pip install --upgrade pip
  - pip install cibuildwheel twine

build_script:
  - cibuildwheel --output-dir wheelhouse

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
          if ($env:APPVEYOR_REPO_TAG_NAME.Contains("rc")) {
              $env:TWINE_REPOSITORY_URL = "https://test.pypi.org/legacy/"
          }
      }
  - cmd: IF "%APPVEYOR_REPO_TAG%"=="true" python -m twine upload wheelhouse\*.whl --skip-existing

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
